### ISSUE TITLE
Performance / overhead and file caching?

### ISSUE THREAD

**Issue by pwFoo** [hacdias/caddy-minify#1]
Hi,

looks like a great new plugin!

But what's about performance / overhead / caching minified files?

Should I use caddy minify plugin or a CMS minify plugin with file caching?
Or is the next planned module a caddy cache module? _g_ ;)

**Comment by hacdias** [comment]
Hello! Thank you for your interest!

Right now, this plugin does everything on-the-fly so, for heavy websites I think it's better a CMS minify plugin with file caching.

But caching can be available in the future :D I'll think about it.

@mholt, is there anything about caching with Caddy?

Thanks :D

**Comment by mholt** [comment]
Caddy uses E-Tag, so at least browsers won't have to request the same resource over and over.

**Comment by pwFoo** [comment]
A cache plugin could save generated / requested content and deliver from cache - if exists. 

A "simple" (?) admin api could be used by http calls (like done with varnish) to 
1. create / update a cached page
2. delete a cached page
3. delete all cached pages belong to the domain / vhost

Optional a simple statistic about cache hits.

Would be a great addition used as webserver or reverse proxy.

**Comment by hacdias** [comment]
Hey @pwFoo! I'll think about it. It would be, indeed, a great feature :D

**Comment by pwFoo** [comment]
Yes, I worry about the time such a cache plugin would need... I haven't any Go / caddy programming knowledge... 

If it's to complex as caddy plugin I'll use varnish as cache proxy ;)

**Comment by hacdias** [comment]
You can use it for now. I'll leave this issue opened so we can see what we can do. It shouldn't be that complicated ;)

**Comment by hacdias** [comment]
Hello!

I've seen that there is someone creating a cache plugin: https://github.com/nicolasazrak/caddy-cache

I'll read more about it!

**Comment by pwFoo** [comment]
Interesting. Thanks for sharing the link!

**Comment by hacdias** [comment]
A cache plugin was created! https://caddyserver.com/docs/http.cache
