### ISSUE TITLE
Minify removes usable code

### ISSUE THREAD

**Issue by stp-ip** [hacdias/caddy-minify#10]
Just noticed, that using minify on this code:
```html
<input type="text" name="name" id="name" placeholder="Name" />
```
is rewritten to:
```html
<input name="name" id="name" placeholder="Name" />
```

This actually breaks sites. Doesn't that this should be intentional. Wanted to log it here for now.

Thanks

**Comment by hacdias** [comment]
We are using tdewolff's engine. You should report this issue here: https://github.com/tdewolff/minify/issues. 😄

**Comment by stp-ip** [comment]
You are right. Forgot about the upstream. Sorry for the noise.
