### ISSUE TITLE
minify removes "%" from inline style in HTML

### ISSUE THREAD

**Issue by Elapo** [hacdias/caddy-minify#11]
So, I'm not sure whether this is intended behaviour, but I stumbled upon an issue recently caused by a missing "%" in an inline style. 

After looking for a while, I found this is caused by minify. I made a simple way to reproduce.

Caddyfile:
```
localhost:8080 {
	root site
	minify
}
```

HTML page:
```
<!doctype html>
<html>
  <head>
    <title>minify-test</title>
  </head>
  <body>
    <div id="colored" style="left:0%"></div>
  </body>
</html>
```

when using the minify directive, `left: 0%` becomes `left: 0`
I realise that in this case `left: 0` and `left: 0%` are identical, but in the production case, the missing "%" was breaking a script.

**Comment by hacdias** [comment]
Sorry, but this issue is not directly related to this repository. You should move this issue to [tdewolff/minify](https://github.com/tdewolff/minify) which is the engine we use 😄 Thanks!
