### ISSUE TITLE
Minify isn't working in combination with errors directive

### ISSUE THREAD

**Issue by cpuschma** [hacdias/caddy-minify#15]
Hi,

I noticed that minify isn't working in combination with the errors [directive](https://caddyserver.com/docs/errors)

Caddyfile:
```
nevolution.me {
        root /var/www/nevolution/httpdocs
        gzip
        header / -Server
        minify
        tls {
                dns cloudflare
        }
        errors {
                404 404.html
        }
}
```

What the source code looks like in my browser if I open the page:

![Proof](https://cdn.pbrd.co/images/GDj1HVJ.png)

**Comment by hacdias** [comment]
That is the correct behavior. Minify only minifies the output of the directives that come after [it in the chain](https://github.com/mholt/caddy/blob/master/caddyhttp/httpserver/plugin.go#L464). I could try to move it down and put it before the errors, though.
