### ISSUE TITLE
[PANIC /path/to/a/file] caddyhttp/httpserver/responsewriterwrapper.go:41 - *minify.minifyResponseWriter is not a closeNotifier

### ISSUE THREAD

**Issue by TooYoungTooSimp** [hacdias/caddy-minify#16]
I come back again......
Happy to see the issue #14 fixed. I updated to the newest version. But I found a bigger problem appeared.
`[PANIC /path/to/a/file] caddyhttp/httpserver/responsewriterwrapper.go:41 - *minify.minifyResponseWriter is not a closeNotifier`
Every time a proxy request starts, this error message appears. So many place of my website became blank.
↓My Caddyfile↓
```
xxx.xxx {
    gzip
    minify
    header / Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"
    internal /template
    root /path/to/my/site
    proxy /api localhost:5000
    proxy /isso localhost:8080 {
        without /isso
    }
    log /var/log/xxx.log
    markdown {
        template basic /template/basic.html
        template post_with_disqus /template/post_with_disqus.html
        template post_with_isso /template/post_with_isso.html
    }
    git {
        repo github.com/xxx/yyy
        interval 30
    }
}
```
All requests to /api and /isso returns 500, and the error message appears.

**Comment by hacdias** [comment]
Sorry, please try downloading it again.

**Comment by TooYoungTooSimp** [comment]
Thank you! I'll have a try right now.

**Comment by TooYoungTooSimp** [comment]
Appreciate for your work! It works!
