### ISSUE TITLE
Minify overwrites 404 on missing resources

### ISSUE THREAD

**Issue by klingtnet** [hacdias/caddy-minify#2]
If I request a missing resouce, e.g. `localhost:12345/missing` then a 500 is returned when the minify directive was specified. This is because minify returns a 500 on missing resources and therefore overwrites caddy's 404 for the requested resource.

How did I run caddy? `caddy -conf caddy.conf`
Caddy test configuration: `caddy.conf`:

``` ini
localhost:12345
log stdout
minify
errors stderr
```

**Comment by klingtnet** [comment]
Log:

```
$ /tmp/foo: caddy -conf caddy.conf
Activating privacy features... done.
http://localhost:12345
WARNING: File descriptor limit 1024 is too low for production servers. At least 8192 is recommended. Fix with "ulimit -n 8192".
19/Aug/2016:10:28:56 +0200 [ERROR 500 /] mime: no media type
::1 - [19/Aug/2016:10:28:56 +0200] "GET / HTTP/1.1" 500 0
19/Aug/2016:10:28:59 +0200 [ERROR 500 /missing] mime: no media type
::1 - [19/Aug/2016:10:28:59 +0200] "GET /missing HTTP/1.1" 500 26
```

**Comment by klingtnet** [comment]
It logs a 500 even if the `index.html` is present:

```
...
19/Aug/2016:10:28:56 +0200 [ERROR 500 /] mime: no media type
::1 - [19/Aug/2016:10:28:56 +0200] "GET / HTTP/1.1" 500 0
...
```

**Comment by hacdias** [comment]
Hello @klingtnet, thanks for reporting this. I've fixed it now :)

C.C.: @mholt, I ask you to update this in caddyserver.com when you've a bit of time. :) Thanks.

**Comment by mholt** [comment]
@hacdias I will update upon the next caddy release. Thanks!
