### ISSUE TITLE
error when placing minify below gzip directive

### ISSUE THREAD

**Issue by SimJoSt** [hacdias/caddy-minify#23]
I put my Caddyfile directives in alphabetical order for better readability, as I have not read that the order matters.
When adding `minify`, I got the following error:
> ERR_CONTENT_DECODING_FAILED

Some post suggested, it might be a problem with the header saying the site is served with gzip, but the content doesn't fit.
So I added the `minify` directive *above* the `gzip` directive and the error didn't exist anymore.
But another one :-) #22

**Comment by hacdias** [comment]
Can't reproduce. Which browser are you using?

My Caddyfile:

```
localhost:8080

browse
gzip
minify
```

**Comment by iamareebjamal** [comment]
Seconded, Chrome Browser, happening even without gzip plugin. I'm reverse proxying the content though

**Comment by theel0ja** [comment]
Same here.

my caddyfile:

```
example.org {
    gzip
    tls letsencrypt@example.org
    minify

    proxy / example-org:80 {
        transparent
    }
}
```

**Comment by faradaytrs** [comment]
Same here [3]

**Comment by hacdias** [comment]
@theel0ja does it happen to you? According to the issue's author, it was supposed to happen only when you put `minify` below `proxy`. Although I can't see how it would do any difference, since it will run on Caddy's defined order.

**Comment by theel0ja** [comment]
Won't work (gzip enabled):
```
www.example.org {
    gzip
    tls letsencrypt@example.org

    header / {
        -Server
        -X-Powered-By

        Strict-Transport-Security "max-age=15552000; includeSubDomains; preload;"

        X-Frame-Options SAMEORIGIN
        Referrer-Policy no-referrer-when-downgrade

        X-Xss-Protection "1; mode=block; report=https://[redacted].report-uri.com/r/d/xss/enforce"
        X-Content-Type-Options nosniff
    }

    proxy / example-org:80 {
        transparent
    }

    minify
}
```

Won't work (disabled gzip):
```
www.example.org {
    tls letsencrypt@example.org

    header / {
        -Server
        -X-Powered-By

        Strict-Transport-Security "max-age=15552000; includeSubDomains; preload;"

        X-Frame-Options SAMEORIGIN
        Referrer-Policy no-referrer-when-downgrade

        X-Xss-Protection "1; mode=block; report=https://[redacted].report-uri.com/r/d/xss/enforce"
        X-Content-Type-Options nosniff
    }

    proxy / example-org:80 {
        transparent
    }

    minify
}
````


However, with another site that is not reverse proxying content, it works.
```
user.example.org {
    gzip
    tls letsencrypt@example.org

    root /var/www/user.example.org
    ext .html
    minify
}
```

**Comment by pfruh** [comment]
Same issue here, reverse proxying three different sites, all with gzip enabled, one is working with minify, the other two are showing the `ERR_CONTENT_DECODING_FAILED` error.

**Update:** It seems this happens if the content from the proxy upstream is already gzipped, since the one site that is working is the only one not using gzip on the upstream.

**Comment by SimJoSt** [comment]
So maybe the minify directive doesn't detect if content is already minified.
So the problem actually might not have to do with the order of the directives at all. Good catch!
Will you look into this @hacdias ?

**Comment by sachk** [comment]
This has been happening to me, it only seems to happen when proxying gzipped content.

**Comment by hacdias** [comment]
Sorry for taking this long. I will take a look at this during the next week! 😄

**Comment by sachk** [comment]
Using minify and gzip in front of ghost is an example that causes this issue.

**Comment by TooYoungTooSimp** [comment]
I got the same problem here....
This time no matter what order I put, ERR_CONTENT_DECODING_FAILED happens.
I tried all the permutations of ["proxy","minify","gzip"]
but if I disable any of (minify|gzip), caddy will work.

**Comment by ricardoboss** [comment]
Same problem

**Comment by ghost** [comment]
Same problem

If the backend server has GZIP enabled, add the minify website caddy does not work.
`http://test.xxxx.com {
    minify
    proxy / http://test.xxxx.com
}`

**Comment by ghost** [comment]
caddyhttp/httpserver/responsewriterwrapper.go:55 - *minify.minifyResponseWriter is not a closeNotifier

**Comment by makew0rld** [comment]
Can confirm

**Comment by delight** [comment]
same here

**Comment by hacdias** [comment]
Due to the recent developments of Caddy (v2!) and the incompatibility of this plugin with newer versions, as well as not being maintained, I'm closing this issue and archiving the repository.
