### ISSUE TITLE
minify: HTTP/2 Server Push 

### ISSUE THREAD

**Issue by elcore** [hacdias/caddy-minify#24]
### 1. What version of Caddy are you using (`caddy -version`)?

Caddy 0.10.4

### 2. What are you trying to do?

Using HTTP/2 Server Push with `http.minify`

### 3. What is your entire Caddyfile?

```text
example.com {
   [...]

    minify
    push /foo/bar.css
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?

/

### 5. Please paste any relevant HTTP request(s) here.

GET https://example.com/ with Chrome/FF

### 6. What did you expect to see?

Pushed `/foo/bar.css `

### 7. What did you see instead (give full error messages and/or log)?

`/foo/bar.css ` is not pushed

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?

1. Use the provided Caddyfile
2. Verify HTTP/2 Server Push with Network Tools or https://http2-push.io

**Comment by sachk** [comment]
Yeah, HTTP push doesn't seem to work for me either with this plugin.

**Comment by hacdias** [comment]
Due to the recent developments of Caddy (v2!) and the incompatibility of this plugin with newer versions, as well as not being maintained, I'm closing this issue and archiving the repository.
