### ISSUE TITLE
Code feedback

### ISSUE THREAD

**Issue by tdewolff** [hacdias/caddy-minify#3]
I'm not sure how else to give feedback than through an issue, but as the minify author I wanted to give some feedback about the plugin:
- [x] https://github.com/hacdias/caddy-minify/blob/master/minify.go#L48 you throw an error here as well, is that really what you want when the mimetype parser fails? I think you should just blindly return any content it wants to send
- [x] You could omit the `sanitizeContentType` and use https://godoc.org/github.com/tdewolff/minify#M.AddRegexp instead for XML and JSON. Possibly also for JS
- [x] https://github.com/hacdias/caddy-minify/blob/master/setup.go#L19 you are adding minifiers by their file extension, but you should use their mimetype (such as `text/html`). That way embedded scripts and styles get minified as well 
- [x] https://github.com/hacdias/caddy-minify/blob/master/minify.go#L62 whenever minification fails, you return an error here. But this is probably not what the user wants. I think it is more useful to emit a warning and return the original content instead. The `Bytes` function will return the original content whenever it encounters an error, so just use that instead and emit a warning
- [ ] I think you should omit the buffer at https://github.com/hacdias/caddy-minify/blob/master/minify.go#L35 and use streams instead, see https://github.com/tdewolff/minify#responsewriter for an example. This lowers memory footprint

**Comment by hacdias** [comment]
Hi @tdewolff!

Thanks for all of the suggestions. Now, I'm working on improving some stuff on File Manager, but I'll do all of this as soon as possible :)

**Edit:** I edited your post formatting.

**Comment by hacdias** [comment]
Hey!

I just pushed a commit with the "fixes" for the first 4 topics you've talked about. Please check them out.

I just can't figure out how to do the buffer thing because I'm using it in line 36.

May you help me?

Thanks! :D

**Comment by hacdias** [comment]
Thanks! Check it out now please. :D

**Comment by tdewolff** [comment]
Looking good!

As to topic 5, I don't fully get what `minifyResponseWriter` does, is that required by Caddy for the `Next` middleware?

Secondly, by implementing a streaming middleware (as opposed to buffering, which it is now), you are unable to set `Content-Length` before writing to the stream, since we just don't know yet how long it will be. By streaming, the minifier and it writing to the response writer would be in a separate goroutine. The middleware and the `Next` would write to a pipe which acts as the reader for the minifier.

This is pretty neat, because if all middleware does that, any write on one end will cause all the middleware that runs concurrently to process it and output the write on the other end. You can handle files of infinite size for example, your memory footprint is a set limit.

This might not work in this case, because you need to know the content-length before writing. Even if you know it after writing everything to the response writer, HTTP can't send it before it knows content-length. So you need to minify so you know the content-length, and then you need a buffer. So I'm afraid there's no way around this.

**Comment by hacdias** [comment]
Hi!

`minifyResponseWriter` is basically used to capture the response from the server without sending it directly to the user. Then, I can use that data and minify it.

Yup, and I need to set `Content-Length` before sending the data.

**Comment by hacdias** [comment]
Hey @tdewolff!

I'll close this issue, as the main "mini-issues" are solved. Unfortunately, I think we can't do anything about the fifth one.

Anyway, thank you everything and for all of your suggestions. They were very helpful! :D
