### ISSUE TITLE
minify.minifyResponseWriter is not a closeNotifier

### ISSUE THREAD

**Issue by hampuskraft** [hacdias/caddy-minify#31]
Hi there,

I'm still able to reproduce #16 with the following configuration:

```
my.domain.name {
  minify
  proxy / localhost:9000 {
    websocket
    transparent
  }
}
```

When sending the first request to the page, this gets spit out in the logs (truncated):

```sh
[PANIC] caddyhttp/httpserver/responsewriterwrapper.go:55 - *minify.minifyResponseWriter is not a closeNotifier
[PANIC /] caddyhttp/httpserver/responsewriterwrapper.go:55 - *minify.minifyResponseWriter is not a closeNotifier
[PANIC /favicon.ico] caddyhttp/httpserver/responsewriterwrapper.go:55 - *minify.minifyResponseWriter is not a closeNotifier
[PANIC /socket.io/?EIO=3&transport=polling&t=MlWcjOV] caddyhttp/httpserver/responsewriterwrapper.go:55 - *minify.minifyResponseWriter is not a closeNotifier
```

For each request, the server is responding with status code 500.
This seems to be the exact issue of #16.

```sh
curl https://getcaddy.com | bash -s personal http.minify,tls.dns.cloudflare
```

I downloaded Caddy and the `http.minify` plugin like above, so I should have the latest version with the fix in #16, right?

Thanks for any help!

Kind regards,
Casper.

**Comment by hacdias** [comment]
Hey @pnfcre. Thanks for the report.

@mholt I see [tdewolff/minify's Response Writer](https://github.com/tdewolff/minify/blob/2028e636bb308ad374847a515d2886fca4a7504d/minify.go#L245) doesn't have Flush, Hijack nor CloseNotify. I believe some plugins won't provide that functionality so how do you recommend me to proceed here?

Previously, on #16, I've just wrapped it, but looking at minify's code, it doesn't seem I should do so.

**Comment by mholt** [comment]
FWIW, in Caddy 2 we've deprecated the CloseNotifier requirement since the need was replaced with context.Context in modern Go versions.

Anyway, there is a helper type to ensure your response writer wrapper implements all the necessary interfaces: https://github.com/caddyserver/caddy/blob/master/caddyhttp/httpserver/responsewriterwrapper.go

Caddy 2 has something similar but with better documentation.

**Comment by hacdias** [comment]
Thanks @mholt! I'll try to use that!

**Comment by SirFitz** [comment]
Hey there, 
I'm able to consistently reproduce this issue now as well with the latest version (Caddy v1.0.4). 
It occurs only when using minify with the header directive:

I installed Caddy and the plugin using: 
`curl https://getcaddy.com | bash -s personal http.ratelimit,http.minify`

Here's my block:

```
my.domain.com { 

   proxy / 10.136.204.55:5005 {
    transparent
   }
   header / {
       -X-Frame-Options
       -x-frame-options
       Strict-Transport-Security "max-age=31536000;"
  }
   minify
   tls exmaple@gmail.com
}
```

and here's the error I'm receiving: 

` [PANIC] httpserver.ResponseWriterWrapper is not a closeNotifier`

Thanks in advance for your help with this! This plugin is great!
Best Regards, 
Romario
