### ISSUE TITLE
Minify breaks error pages

### ISSUE THREAD

**Issue by stp-ip** [hacdias/caddy-minify#7]
Using the current downloadable version.
Wanted to log it here. Maybe I can check, if it is fixed on master.

Error page will output as code and not render with minify enabled. Also it won't be minified.

**Comment by wayneashleyberry** [comment]
Having the same problem - see original issue here: https://github.com/mholt/caddy/issues/1270#issue-190741214

Complete Caddyfile:

```
https://wearenext.co.za {
    gzip
    minify
    root /home/devops/site

    git git@github.com:we-are-next/next-website.git {
       then hugo --destination=/home/devops/site
    }

    expires {
        match .css$ 1y
        match .js$ 1m
        match .png$ 1d
        match .jpg$ 1h
        match .pdf$ 1i
        match .txt$ 1s
        match .html$ 5i30s
    }

    errors {
        404 404.html
    }
}

http://139.59.170.79:80 {
    redir https://wearenext.co.za{uri}
}

http://wearenext.co.za:80 {
    redir https://wearenext.co.za{uri}
}

http://www.wearenext.co.za:80 {
    redir https://wearenext.co.za{uri}
}

https://www.wearenext.co.za {
    redir https://wearenext.co.za{uri}
}
```

**Comment by hacdias** [comment]
Hello!!! Sorry for the delay, can you try it using the branch master, please?

**Comment by stp-ip** [comment]
sorry for not getting back. tested it with the new v0.10 release of caddy and the latest upload on the plugin page. seems to been resolved. Thanks.

**Comment by hacdias** [comment]
You're welcome :)
