### ISSUE TITLE
<pre> regression -- Caddy needs to update tdewolff/minify in buildsrv

### ISSUE THREAD

**Issue by ghost** [hacdias/caddy-minify#8]
:smile: Been looking into a problem with tags inside pre elements. After checking with tdewolff/minify#115, and reading through [caddyserver/buildsrv/blob/master/server/build.go#L37](https://github.com/caddyserver/buildsrv/blob/master/server/build.go#L37), I went and saw issue caddyserver/buildsrv#36.

TL;DR there was a regression in [tdewolff/minify](https://github.com/tdewolff/minify), fixed in August, that needs to be merged into the available version of your plugin from the Caddy download site. I have built your plugin into the latest source version of Caddy using `go get` and can confirm it fixes the issue. Thank you in advance and keep up the great work. 👍

**Comment by hacdias** [comment]
Hello @Nycroth! In this moment what we can do is to @mholt to update the server, but soon we, developers, will be enabled to update the plugins when we want them to be updated 😄

**Comment by mholt** [comment]
Sorry. Build from source for now. Will get around to it! Classes just started...

**Comment by mholt** [comment]
Just updated the build server.
