### ISSUE TITLE
minify deletes :root-declaration in css

### ISSUE THREAD

**Issue by vedam** [hacdias/caddy-minify#9]
in CSS-files

declaration of custom-properties in :root-selector:
```
:root {
  --side-padding: 2rem;
}
```

style-declaration using the css custom-properties:
```
.side-padding {
  padding-left: var(--side-padding);
  padding-right: var(--side-padding);
}
```

with minify the :root-declaration is deleted, so custom-properties in style-declaration couldn't work

**Comment by hacdias** [comment]
Hello @vedam! That issue is not related to this repository unfortunately. The correct place for it should be on [tdewolff/minify](https://github.com/tdewolff/minify) repository 😄 I ask you to open the issue there please! 

Thanks!
